name: CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.zig'
      - '**.yml'
  push:
    branches:
      - main
    paths:
      - '**.zig'
      - '**.yml'

jobs:
  test:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - name: Run Test
        run: zig build test
      - name: Memory leak detect
        run: |
          sudo apt update && sudo apt install -y valgrind
          zig build -Dcpu=baseline --verbose
          TEST_BINARY=./zig-out/bin/demo
          valgrind --leak-check=full --tool=memcheck \
          --show-leak-kinds=all --error-exitcode=1 ${TEST_BINARY} --output a.out \
          hello world

  cross-compile:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        targets: [x86_64-windows, x86_64-linux, x86_64-macos, aarch64-macos]
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - name: Build demo
        run: |
          zig build -Dtarget=${{ matrix.targets }}
